name: icd_in_adf2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Installs Node and the npm packages saved in build/package.json
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x

      # (optional) quick check so you can see the build folder is there
      - name: Sanity check workspace
        run: |
          echo "pwd=$(pwd)"
          ls -la
          echo "--- build dir ---"
          ls -la build || true

      - name: install ADF Utilities package
        working-directory: build
        run: npm install

      # Validates all of the Data Factory resources in the repository.
      - name: Validate
        working-directory: build
        run: |
          RESOURCE_ID="/subscriptions/48773b9f-3806-4461-bb01-3e2a4253f178/resourceGroups/re_group987/providers/Microsoft.DataFactory/factories/datafactoryclass543"
          npm run build validate "$GITHUB_WORKSPACE/" "$RESOURCE_ID"

      # Export ARM template & parameters
      - name: Validate and Generate ARM template
        working-directory: build
        run: |
          RESOURCE_ID="/subscriptions/48773b9f-3806-4461-bb01-3e2a4253f178/resourceGroups/re_group987/providers/Microsoft.DataFactory/factories/datafactoryclass543"
          npm run build export "$GITHUB_WORKSPACE/" "$RESOURCE_ID" "ExportedArmTemplate"

      # Upload the exported template as an artifact
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: build/ExportedArmTemplate

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Download the artifact into a folder named ExportedArmTemplate
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ExportedArmTemplate

      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: re_protect
          dataFactoryName: datafactoryprotcect
          armTemplateFile: ExportedArmTemplate/ARMTemplateForFactory.json
          armTemplateParametersFile: ExportedArmTemplate/ARMTemplateParametersForFactory.json
          # If your parameters file requires the factory name, uncomment and ensure the key matches your JSON:
